name:                aesa-atom
version:             0.1.0.0
github:              "ugeorge/saab-aesa"
license:             BSD3
author:              "George Ungureanu"
maintainer:          "ugeorge@kth.se"
copyright:           "2019 George Ungureanu, KTH"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ugeorge/saab-aesa>

dependencies:
- base >= 4.7 && < 5
- forsyde-atom
- forsyde-atom-extensions
- parallel

library:
  source-dirs: src

executables:
  aesa-hl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -eventlog 
    - -with-rtsopts=-N
    dependencies:
    - aesa-atom
    - directory
    - process
    - bytestring-lexing
    - bytestring
    - double-conversion
    - deepseq
    - parallel
    
tests:
  tests-hl:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aesa-atom
