name:                aesa-atom
version:             0.2.0.0
github:              "ugeorge/saab-aesa"
license:             BSD3
author:              "George Ungureanu"
maintainer:          "ugeorge@kth.se"
copyright:           "2019 George Ungureanu, KTH"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ugeorge/saab-aesa>

dependencies:
- base >= 4.7 && < 5
- forsyde-atom
- forsyde-atom-extensions
# for the executables
- directory
- filepath
- process
- bytestring-lexing
- bytestring
- double-conversion
- deepseq
- parallel
- random

library:
  source-dirs: src

executables:
  aesa-cube:
    main:                Cube.hs
    source-dirs:         app
    ghc-options:
    - -main-is           Cube
    - -threaded
    - -rtsopts
    - -eventlog 
    - -with-rtsopts=-N
    dependencies:
    - aesa-atom
  aesa-stream:
    main:                Stream.hs
    source-dirs:         app
    ghc-options:
    - -main-is           Stream
    - -threaded
    - -rtsopts
    - -eventlog 
    - -with-rtsopts=-N
    dependencies:
    - aesa-atom
    
tests:
  tests-cube:
    main:                SpecCube.lhs
    source-dirs:         test
    ghc-options:
    - -main-is           SpecCube
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aesa-atom
    - QuickCheck
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
  tests-stream:
    main:                SpecStream.lhs
    source-dirs:         test
    ghc-options:
    - -main-is           SpecStream
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aesa-atom
    - QuickCheck
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
