resolver: lts-18.8

# packages:
#  - location:
#     git: git@github.com:forsyde/forsyde-atom.git
#     commit: 59aeeb6130bc3fa4665aebd2634ebe3a575a7208
#    extra-dep: true

packages:
- .
- ../forsyde-atom-extensions

extra-deps:
- normaldistribution-1.1.0.3
- git: git@github.com:forsyde/forsyde-atom.git
  commit: 76b0c8b07047180cdef2a58c696e5245e7db3ce3

# Override default flag values for local packages and extra-deps
# flags: {}
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
