resolver: lts-9.4

packages:
- .
- ../forsyde-atom-extensions
# - ../forsyde-deep-extensions
# - ../../forsyde/forsyde-deep
- ../aesa-atom

extra-deps:
# extra-deps:
- parameterized-data-0.1.6
- type-level-0.3.0
- QuickCheck-2.10.1
# - forsyde-deep-0.2.0
- type-level-natural-number-2.0
- git: git@github.com:forsyde/forsyde-atom.git
  commit: 76b0c8b07047180cdef2a58c696e5245e7db3ce3
- git: git@github.com:ugeorge/forsyde-deep.git
  commit: 482a972e3f99c627c01181c071bc2d0c91591878
