resolver: lts-11.13

packages:
- .
- ../aesa-atom
- ../forsyde-atom-extensions
- ../forsyde-shallow-extensions

extra-deps:
- normaldistribution-1.1.0.3
- forsyde-shallow-3.4.0.0
- git: git@github.com:forsyde/forsyde-atom.git
  commit: 76b0c8b07047180cdef2a58c696e5245e7db3ce3
