resolver: lts-11.13

packages:
- .
- ../aesa-atom
- ../forsyde-atom-extensions
- ../forsyde-shallow-extensions

extra-deps:
- forsyde-shallow-3.4.0.0
- git: git@github.com:forsyde/forsyde-atom.git
  commit: 59aeeb6130bc3fa4665aebd2634ebe3a575a7208
